# Generated by Django 3.0.7 on 2021-09-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.CharField(max_length=100)),
                ('login', models.TextField(blank=True, null=True)),
                ('displayName', models.TextField(blank=True, null=True)),
                ('pictureId', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
